### ISSUE TITLE
Процесс генерации кода

### ISSUE THREAD

**Issue by j0t** [Koziev/rusyllab#3]
Добрый день! 
Это скорее вопрос, чем проблема. 
Похоже, что код на питоне был сгенерен из чего-то другогоː
`# autogenerated 2019-01-19 10:52:09.746954`
Нельзя ли узнать подробнее о процессе генерации, с помощью чего и из чего?
Меня интересуют формальные правила слогоделения русского языка,
не подскажете, где их можно найти, или что было взято за основу?

Спасибо.

**Comment by Koziev** [comment]
Добрый день,

питоновский код получен конвертацией правил вот отсюда: https://github.com/Koziev/GrammarEngine/blob/master/src/dictionary.src/rus_syllab_rules.sol

**Comment by j0t** [comment]
O, очень интересно, спасибо!
